# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xa7a35tcpg236-1I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Asus/Desktop/receiver/receiver.cache/wt [current_project]
set_property parent.project_path C:/Users/Asus/Desktop/receiver/receiver.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Asus/Desktop/receiver/receiver.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Asus/Desktop/receiver/receiver.srcs/sources_1/new/receiver.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Asus/Desktop/receiver/receiver.srcs/constrs_1/new/pins.xdc
set_property used_in_implementation false [get_files C:/Users/Asus/Desktop/receiver/receiver.srcs/constrs_1/new/pins.xdc]


synth_design -top receiver -part xa7a35tcpg236-1I


write_checkpoint -force -noxdef receiver.dcp

catch { report_utilization -file receiver_utilization_synth.rpt -pb receiver_utilization_synth.pb }
